config/routes.rb
QuickEvent::Application.routes.draw do

namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
    resources :users
      resources :users do
        resources :events
      end
    resources :sessions, only: [:create, :new, :destroy]
    end
 end

  resources :users do
    resources :events
  end
  resources :users
  resources :sessions, only: [:create, :new, :destroy]
  root :to => "sessions#new"

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  attr_accessible :address, :description, :name
end

app/controllers/api/v1/events_controller.rb
module Api
  module V1
   class EventsController < ApplicationController
  # GET users/1/events.json
  #before_filter :restrict_access
    def index
      @user = User.find(params[:user_id])
      @events = @user.events

      respond_to do |format|
      format.json { render :json => @events }
      end
    end

  # GET users/1/events/1.json
    def show
      @user = User.find(params[:user_id])
      @event = @user.events.find(params[:id])

      respond_to do |format|
      format.json { render :json => @event }
      end
    end

  # POST users/1/events.json
    def create
      @user = User.find(params[:user_id])
      @event = @user.events.build(params[:event])

      respond_to do |format|
        if @event.save
        format.json { render :json => @event, :status => :created, :location => [@event.user, @event] }
        else
        format.json { render :json => @event.errors, :status => :unprocessable_entity }
        end
      end
    end

  # PUT users/1/events/1.json
    def update
      @user = User.find(params[:user_id])
      @event = @user.events.find(params[:id])

      respond_to do |format|
        if @event.update_attributes(params[:event])
          format.json { head :ok }
        else
          format.json { render :json => @event.errors, :status => :unprocessable_entity }
        end
      end
    end

  # DELETE users/1/events/1.json
    def destroy
      @user = User.find(params[:user_id])
      @event = @user.events.find(params[:id])
      @event.destroy

      respond_to do |format|
        format.json { head :ok }
      end
    end
   end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET users/1/events
  # GET users/1/events.json
  def index
    @user = User.find(params[:user_id])
    @events = @user.events

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @events }
    end
  end

  # GET users/1/events/1
  # GET users/1/events/1.json
  def show
    @user = User.find(params[:user_id])
    @event = @user.events.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @event }
    end
  end

  # GET users/1/events/new
  # GET users/1/events/new.json
  def new
    @user = User.find(params[:user_id])
    @event = @user.events.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @event }
    end
  end

  # GET users/1/events/1/edit
  def edit
    @user = User.find(params[:user_id])
    @event = @user.events.find(params[:id])
  end

  # POST users/1/events
  # POST users/1/events.json
  def create
    @user = User.find(params[:user_id])
    @event = @user.events.build(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to([@event.user, @event], :notice => 'Event was successfully created.') }
        format.json { render :json => @event, :status => :created, :location => [@event.user, @event] }
      else
        format.html { render :action => "new" }
        format.json { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT users/1/events/1
  # PUT users/1/events/1.json
  def update
    @user = User.find(params[:user_id])
    @event = @user.events.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to([@event.user, @event], :notice => 'Event was successfully updated.') }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE users/1/events/1
  # DELETE users/1/events/1.json
  def destroy
    @user = User.find(params[:user_id])
    @event = @user.events.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to user_events_url(user) }
      format.json { head :ok }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for([@event.user, @event]) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', [@event.user, @event] %> |
<%= link_to 'Back', user_events_path(@event.user) %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.name %></td>
    <td><%= event.description %></td>
    <td><%= event.address %></td>
    <td><%= link_to 'Show', [event.user, event] %></td>
    <td><%= link_to 'Edit', edit_user_event_path(event.user, event) %></td>
    <td><%= link_to 'Destroy', [event.user, event], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_user_event_path(params[:user_id]) %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', user_events_path(@event.user) %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @event.name %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>

<p>
  <b>Address:</b>
  <%= @event.address %>
</p>


<%= link_to 'Edit', edit_user_event_path(@event.user, @event) %> |
<%= link_to 'Back', user_events_path(@event.user) %>